/* CH32V203G6 */
MEMORY
{
    /* Code Flash, 224KB max */
	FLASH : ORIGIN = 0x08000000, LENGTH = 32k
    /* SRAM, 64KB max */
	RAM : ORIGIN = 0x20000000, LENGTH = 10k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

